### ISSUE TITLE
Stat exceeds integer value

### ISSUE THREAD

**Issue by BWagener** [lpradel/steam-web-api-java#20]
I've seen an error in my logs which suggests that stats returned by the steam GetUserStatsForGame API can exceed integer values:
```
Caused by: com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (4294967260) out of range of int (-2147483648 - 2147483647)
 at [Source: (String)"{"playerstats":{"steamID":"76561198121152748","gameName":"Mordhau","stats":[{"name":"GameVersion","value":502402884},{"name":"FunRank","value":4294967260},{"name":"FunRankSamples","value":5004},{"name":"HeadsDecapitated","value":2988},{"name":"MeleeHeadHits","value":13891},{"name":"MeleeTorsoHits","value":70308},{"name":"MeleeLegHits","value":19546},{"name":"ProjectileHeadHits","value":473},{"name":"ProjectileTorsoHits","value":2620},{"name":"ProjectileLegHits","value":346},{"name":"FistKills",""[truncated 2071 chars]; line: 1, column: 154]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInputCoercion(ParserMinimalBase.java:637) ~[jackson-core-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(ParserMinimalBase.java:606) ~[jackson-core-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:979) ~[jackson-core-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:887) ~[jackson-core-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:710) ~[jackson-core-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:526) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:506) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.lukaspradel.steamapi.webapi.client.SteamWebApiClient.processRequest(SteamWebApiClient.java:40) ~[steam-web-api-1.4.2.jar:?]
```

App ID: 629760
Steam User ID: 76561198121152748

I suggest the Stat class' value field to be changed to Long

Cheers

**Comment by lpradel** [comment]
Huh, well that's interesting. Thanks for pointing this out. Will try to fix it ASAP.

**Comment by lpradel** [comment]
I have a fix prepared for this issue, however I can't verify it at the moment. With my Steam API key I am getting 403 for Steam API for all user/app combinations I'm trying. Is it just me/my key or is not working for you either?

**Comment by BWagener** [comment]
I think it is having issues right now.
I've had this problem today as well.

Although I run a service that queries this API using your library which is running fine so I'm not sure what might be the issue or whether it's related to our web API keys.

**Comment by lpradel** [comment]
Well I'm still getting the 403 problem, but I was able to reproduce via unit test. Since I'll be away for vacation starting tomorrow I decided to go ahead with it anyway and release the fix as 1.5.0. as it sort of breaks the lib API. Should be available tomorrow or the day after on Mvn Central. Let me know if you find any issues.

**Comment by BWagener** [comment]
Great, thank you so much!

I'll test the release as soon as possible and report back.

**Comment by BWagener** [comment]
The problem is resolved. Thanks again!
